---
abstract: 'Collection of scripts to manage retrieval, parsing, loading of config and PM files from RAN management systems.'
author:
  - 'Hartmut Behrens <hartmut.behrens@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: alcatel-lucent
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ran_db
no_index:
  directory:
    - etc
    - inc
    - templates
requires:
  App::Cmd: 0
  Archive::Tar: 0
  Compress::Zlib: 0
  DBD::mysql: 0
  DBI: 0
  Fcntl: 0
  File::Path: 0
  IO::Uncompress::Gunzip: 0
  Memoize: 0
  Net::FTP: 0
  Time::Local: 0
  XML::Bare: 0
  XML::LibXML: 0
  XML::Simple: 0
resources:
  repository: git://github.com/hartmutbehrens/ran_db.git
version: 0.01
